# main variables for game state

WIDTH = 1024 #768
HEIGHT = 768 #576
FPS = 60
TITLE = "Mandelbrothers"
BACKGROUND_COLOR = (0,0,0)
TILESIZE = 64
GRID_W = WIDTH / TILESIZE
GRID_H = HEIGHT / TILESIZE

PLAYER_SPEED = 250
PROJECTILE_SPEED = 800
PROJECTILE_LIFETIME = 600
PROJECTILE_RATE = 500
PROJECTILE_DAMAGE = 50
ENEMY_COOLDOWN = 1000
MOB_RADIUS = 50

ITEMS = {"money": 0, "health": 100, "overVisit": 1, "shopVisit": 0}
VISITS = {"shop": False}
